services:
  backend:
    build:
      context: ./backend
    environment:
      - PORT=8000
      - DATABASE_URL=postgres://postgres:password@db:5432/prod
    depends_on:
      - db
    restart: always

  nginx:
    image: nginx:1.27.4-alpine3.21
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./certs:/etc/nginx/ssl
    depends_on:
      - backend
    restart: always

  db:
    image: postgres:17.2-alpine3.21
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=prod
    ports:
      - "127.0.0.1:5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
